#!/bin/bash
set -x
TELEGRAM_API_URL="https://api.telegram.org/bot7910567095:AAFpzdiCEmm7fmAfrN2Uj9-AuXvGrVhIddM/sendMessage"
CHAT_ID="7910567095"
#7910567095:AAFpzdiCEmm7fmAfrN2Uj9-AuXvGrVhIddM

if [ "$#" -eq 0 ]; then
	echo "Usage: $0 <service1> <service2> ..."
	exit 1
fi

if [ $(id -u) -ne 0 ]; then
	echo "Must be run as root"
	exit 1
fi
send_telegram_notification() {
	local message="$1"
	curl -s -X POST "$TELEGRAM_API_URL" -d "chat_id=$CHAT_ID&text=$message" > /dev/null
}

check_service_status(){
	systemctl is-active --quiet "$1"
}

check_service_exists(){
	#systemctl list-unit-files --type=service | awk '{print $1}' | grep -q "$1.service"
	systemctl list-unit-files  | grep -q "$1"
}

restart_service(){
	systemctl restart "$1"
	sleep 2
	check_service_status "$1"
}

while true
do
  for service in "$@"; do
    if check_service_exists "$service"; then
	echo "Service $service"
      if ! check_service_status "$service"; then
        send_telegram_notification "Service $service not running. Try to restart..."
	  if restart_service "$service"; then
	    send_telegram_notification "Service $service restarted."
	  else
	    send_telegram_notification "Service $service restart failed."
	  fi
      fi
    else
      send_telegram_notification "Service $service does not exists."
    fi
  done
sleep 60
done
